### ISSUE TITLE
commit fantastici e dove trovarli

### ISSUE THREAD

**Issue by rcastellotti** [fontafederico/leenucs#1]
`packages.microsoft.gpg`

**Comment by rcastellotti** [comment]
ok quello e' stato il taglio
`Input-Font.zip` e' stato metterci il sale dentro

**Comment by fontafederico** [comment]
oh yes, e non sai la merda che ti perdi tra i commit nei repo privati

**Comment by rcastellotti** [comment]
"perdi"
